version: '3.4'

services:
  gateway:
    image: karthikeyan51/tms-gatewayapi
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
